export const GET_SPOTS_SUCCESS = 'GET_SPOTS_SUCCESS';
export const GET_SPOTS_FAILURE = 'GET_SPOTS_FAILURE';
export const POST_SPOT_SUCCESS = 'POST_SPOT_SUCCESS';
export const POST_SPOT_FAILURE = 'POST_SPOT_FAILURE';
export const GET_FAVOURITES_SPOT_SUCCESS = 'GET_FAVOURITES_SPOT_SUCCESS';
export const POST_FAVOURITES_SPOT_SUCCESS = 'POST_FAVOURITES_SPOT_SUCCESS';
export const DELETE_FAVOURITES_SPOT_SUCCESS = 'DELETE_FAVOURITES_SPOT_SUCCESS';